# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brazo Solidario
email: brazosolidario@gmail.com
  
baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site
url: "marcciosilva.github.io/brazo-solidario"

#sidebar
default-image: logo-placeholder.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: Marccio Silva
copyright:
   name: Brazo Solidario
   link: 'http://brazosolidario.org'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-90322340-1

# Comments
disqus-shortname: brazosolidario

#social
facebook: http://www.facebook.com/brazosolidario
twitter: http://twitter.com/@brazosolidario
instagram: http://instagram.com/brazosolidario

#facebook like box
fb-app-id: 838139559633725
fb-page-url: https://www.facebook.com/brazosolidario/
fb-page-title: Brazo Solidario

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

